export const _id = (index: number) => `e99f09a7-dd88-49d5-b1c8-1daf80c2d7b${index}`;

export const _times = (index: number) =>
  // 'MM/DD/YYYY'
  [
    '11/08/2023',
    '04/09/2024',
    '09/12/2023',
    '01/01/2024',
    '04/23/2024',
    '02/29/2024',
    '05/14/2024',
    '01/13/2024',
    '06/22/2024',
    '10/05/2023',
    '07/11/2024',
    '05/22/2024',
    '03/29/2024',
    '08/29/2023',
    '11/19/2023',
    '10/24/2023',
    '12/02/2023',
    '02/13/2024',
    '09/19/2023',
    '04/17/2024',
    '12/18/2023',
    '06/27/2024',
    '10/19/2023',
    '08/09/2024',
  ][index];

export const _fullName = (index: number) =>
  [
    'Ananya Sharma',
    'Meera Rajput',
    'Sofia Almeida',
    'Priya Nair',
    'Hannah Whitfield',
    'Divya Menon',
    'Grace Okafor',
    'Ritika Bose',
    'Laura Bennett',
    'Ayesha Siddiqui',
    'Neha Kulkarni',
    'Emily Vasquez',
    'Sanjana Iyer',
    'Rebecca Lindgren',
    'Tanvi Deshmukh',
    'Chloe Marchand',
    'Kavya Reddy',
    'Nadia Haddad',
    'Ishita Banerjee',
    'Maya Petrova',
    'Shruti Gokhale',
    'Amara Nwosu',
    'Pooja Chandran',
    'Lena Fischer',
  ][index];

export const _careTeam = (index: number) =>
  [
    'Sunrise Midwifery',
    'Nurture Collective',
    'Bloom Womens Health',
    'Cradle Care Clinic',
    'Lotus Birth Centre',
    'Willow Lactation',
    'Harmony Pelvic Health',
    'Nest Postnatal Care',
    'Serene Mind Counselling',
    'Aarogya Maternity',
    'Meadow Family Practice',
    'Anchor Doula Network',
    'Nurture Collective',
    'Sunrise Midwifery',
    'Cradle Care Clinic',
    'Bloom Womens Health',
    'Willow Lactation',
    'Lotus Birth Centre',
    'Nest Postnatal Care',
    'Harmony Pelvic Health',
    'Aarogya Maternity',
    'Serene Mind Counselling',
    'Anchor Doula Network',
    'Meadow Family Practice',
  ][index];

export const _boolean = (index: number) =>
  [
    true,
    false,
    true,
    false,
    true,
    true,
    true,
    false,
    false,
    true,
    false,
    true,
    true,
    false,
    true,
    false,
    false,
    true,
    false,
    false,
    false,
    true,
    true,
    false,
  ][index];

export const _postTitles = (index: number) =>
  [
    'The fourth trimester: what actually happens in the first 12 weeks',
    'Healing after a C-section, week by week',
    'Latching 101: positions that take the pain out of feeding',
    'Baby blues or postpartum depression? How to tell the difference',
    'Sleep in shifts: a realistic rest plan for new parents',
    'Pelvic floor recovery without the guesswork',
    'What to eat when you are too tired to cook',
    'Rebuilding core strength safely after birth',
    'Perineal care: the first two weeks',
    'When your milk supply dips — and what actually helps',
    'Postpartum anxiety is more common than you think',
    'A gentle return to movement: walking, breathing, stretching',
    'Bottle, breast, or both: feeding without the guilt',
    'How partners can carry more of the postpartum load',
    'Understanding postpartum bleeding and when to call someone',
    'Bonding takes time — and that is completely normal',
    'Mastitis: early signs and same-day relief',
    'Going back to work: pumping, storage and scheduling',
    'Postpartum hair loss, skin changes and other surprises',
    'Contraception options while breastfeeding',
    'Night feeds without losing your mind',
    'Building a village: who to ask for help and how',
    'Your six-week check-up: questions worth asking',
    'Signs your recovery needs medical attention today',
  ][index];

export const _description = (index: number) =>
  [
    'A week-by-week guide to what your body and mind go through after birth, and which changes are worth flagging to your care team.',
    'Wound care, pain relief and the movement restrictions that matter — plus when scar tenderness stops being normal.',
    'Small adjustments to positioning and hold that resolve most of the pain new mothers report in the first fortnight.',
    'A practical screening walkthrough, including the EPDS questions and what a raised score should trigger.',
    'How to split the night with a partner or helper so each of you gets one uninterrupted stretch of sleep.',
    'Simple daily exercises, red flags for prolapse, and when to be referred to a pelvic health physiotherapist.',
    'Twelve one-hand meals built around iron, protein and hydration for the weeks when cooking is not happening.',
    'Why crunches come last, what diastasis recti actually means, and a four-stage progression back to strength.',
    'Sitz baths, ice, stitches and hygiene — the small routines that make the first fourteen days far more comfortable.',
    'The usual causes of a supply dip, what to try first, and the point at which a lactation consultant should be looped in.',
    'Intrusive thoughts, racing heart, hypervigilance — how postpartum anxiety presents and what treatment looks like.',
    'A four-week reintroduction plan that respects healing tissue while rebuilding stamina and mood.',
    'An evidence-based look at mixed feeding, and how to make the choice that keeps mother and baby fed and well.',
    'Concrete tasks a partner can own, from night feeds to appointment logistics to protecting recovery time.',
    'What is normal for lochia, how it changes over six weeks, and the symptoms that mean call now.',
    'Why attachment is a process rather than a moment, and what helps when the feeling has not arrived yet.',
    'Recognising blocked ducts before they escalate, and the self-care steps that resolve most cases quickly.',
    'Pump schedules, milk storage rules and the conversations to have with an employer before the first day back.',
    'The hormonal changes behind shedding, breakouts and pigmentation, and roughly when they settle.',
    'How each method interacts with milk supply, and the timing considerations for the first postpartum year.',
    'Lighting, feeding setup and wind-down routines that keep night wakings short and get everyone back to sleep.',
    'Mapping practical, emotional and clinical support — and scripts for asking without feeling like a burden.',
    'A checklist to take to the postnatal review so nothing important gets skipped in a ten-minute appointment.',
    'Fever, heavy bleeding, chest pain, severe headache — the symptoms that warrant urgent care rather than a wait.',
  ][index];

export const _taskNames = (index: number) =>
  [
    `Review flagged mood screenings`,
    `Approve new lactation article`,
    `Assign care team to 6 new mothers`,
    `Follow up on missed week-2 check-ins`,
    `Update the C-section recovery programme`,
    `Verify midwife credentials`,
    `Moderate community posts`,
    `Publish this week's content digest`,
    `Audit push notification schedule`,
    `Refresh the six-week check-up checklist`,
    `Respond to escalated support tickets`,
    `Translate onboarding copy to Hindi`,
    `Reconcile clinic referral list`,
    `Export monthly recovery outcomes`,
    `Retire outdated feeding guidance`,
    `QA the new symptom tracker`,
    `Schedule partner webinar`,
    `Review consent and privacy copy`,
    `Rebalance care team caseloads`,
    `Archive completed programmes`,
    `Check EPDS scoring thresholds`,
    `Onboard two new counsellors`,
    `Plan the postpartum nutrition series`,
    `Review app store feedback`,
  ][index];
